add commit
rajlful/hik pull request #1
Opened 2021-05-31 16:16 UTC by rajlful

2021-06-02 09:55 UTC, Roxe322 requested changes

2021-06-02 09:55 UTC, Roxe322 commented on hikisapi.py
> +        device_status = requests.get(f'http://{self.ipaddr}:{self.port}/ISAPI/System/status',
Лучше из init метода не делать таких проверок, а вынести в отдельный метод и вызывать его там, где необходимо проверить статус

2021-06-02 09:55 UTC, Roxe322 commented on hikisapi.py
> +        if device_status == 400:
Вместо статус-кодов цифрами лучше пользоваться данными из енам-а, так нагляднее https://docs.python.org/3/library/http.html#http.HTTPStatus

2021-06-02 09:55 UTC, Roxe322 commented on hikisapi.py
> +        device_info = requests.get(f'http://{self.ipaddr}:{self.port}/ISAPI/System/deviceinfo',
Я бы сделал отдельный private-метод, который будет делать запросы, а остальные методы будут его вызывать. Так удобнее потом делать какое-то логирование или обработку ошибок соединения. Кроме того, базовый хост апишки можно в константу тоже вынести

2021-06-02 09:55 UTC, Roxe322 commented on hikisapi.py
> +        width = dict_with_all_capabilities['StreamingChannel']['Video']['videoResolutionWidth']['@opt'].split(',')
dict_with_all_capabilities['StreamingChannel']['Video'] можно вынести в отдельную переменную, тк повторяется в строках ниже

2021-06-02 09:55 UTC, Roxe322 commented on hikisapi.py
> +        dict_with_all_capabilities = xmltodict.parse(device_capabilities.text)
dict_with_all_capabilities - не очень корректное название. Во-первых, в названии переменной не надо указывать ее тип, для этого есть аннотации типов. Вот как раз device_capabilities тут лучше бы подошло

2021-06-02 09:55 UTC, Roxe322 commented on hikisapi.py
> +    def get_device_capabilities(self, stream='101'):  #101 - основной поток камеры. 102 - субпоток
лучше строки 101/102 вынести в константы. Это аналогично https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5) , но со строками)

2021-06-02 09:55 UTC, Roxe322 commented on hikisapi.py
> +        restoring = requests.put(f'http://{self.ipaddr}:{self.port}/ISAPI/System/factoryReset',
тут аналогичные ошибки

2021-06-02 16:46 UTC, Roxe322 commented on hikisapi.py
> +    def __sent_request(self, method, path):
только send, а не sent )

2021-06-02 16:46 UTC, Roxe322 commented on hikisapi.py
> +        HOST = f'http://{self.ipaddr}:{self.port}/ISAPI'
можно простановку этой константы вынести в init, чтоб ее не создавать на каждый вызов)

2021-06-02 16:46 UTC, Roxe322 commented on hikisapi.py
> +        dict_with_useful_capabilities = { 'resolutions' : resolutions,
Опять проблема с типом данных в названии переменной )

2021-06-02 16:46 UTC, Roxe322 commented on hikisapi.py
> +    a = Hikvision('172.16.13.70', 'admin', 'Admin321678')
вот эти вещи лучше спрятать примерно также как прятали в боте на первом занятии)

2021-06-08 08:08 UTC, Roxe322 commented on hikisapi.py
> +    def set_datetime_manual(self, user_date_time):
```
def set_datetime_manual(self, user_date_time):
    status = self.is_device_status_ok()
    if not status:
        raise ValueError('Error')
    datetime_settings = xmltodict.parse(settings.time_settings)
    datetime_settings['Time']['localTime'] = user_date_time
    our_time_settings = xmltodict.unparse(datetime_settings)
    self.__send_request('put', f'/System/time', our_time_settings)
    return our_time_settings
```

2021-06-08 22:08 UTC, Roxe322 commented on hikisapi.py
> +        self.ipaddr = ipaddr
лучше так не сокращать) ip_address

2021-06-08 22:08 UTC, Roxe322 commented on hikisapi.py
> +        logger = logging.getLogger('camera_return')
Эти настройки делаются на уровне модуля, или даже в отдельном файле, дальше просто достаешь getLogger нужный логгер, который ты где-то настроил и используешь. Сейчас у тебя настройка логгера происходит каждый вызов метода :)

2021-06-08 22:08 UTC, Roxe322 commented on hikisapi.py
> +        if device_status == HTTPStatus.OK:
можно сделать просто return device_status == HTTPStatus.OK - это уже или True или False

2021-06-08 22:08 UTC, Roxe322 commented on hikisapi.py
> +            print(decoded_event)
про чистоту функций забыли? :) Давай она будет возвращать список ивентов, а дальше ты будешь их выводить, если нужно :)

2021-06-08 22:08 UTC, Roxe322 commented on hikisapi.py
> +        with open('configuration_data', 'wb') as config:
вот тут аналогично про чистые функции. Функция называется GET_config, а по факту она пишет что-то в файл)

2021-06-08 22:08 UTC, Roxe322 commented on settings.py
> +ipaddr='172.16.13.70'
Я все еще вижу в пулл реквесте данные от твоей камеры :)

2021-06-08 22:08 UTC, Roxe322 commented on hikisapi.py
> +import logging
https://www.python.org/dev/peps/pep-0008/#imports

2021-06-09 08:43 UTC, rajlful commented on hikisapi.py
> +            print(decoded_event)
Она их шлет непрерывно, пока не прервешь. В идеале я думал, что это будет выглядеть так - мы пишем эти ивенты в нашу БД(не все ивенты, а только нужные). Затем, если есть нужда, в нашей программе из БД мы эти ивенты запрашиваем в журнал. Как это лучше тогда сделать ?

2021-06-09 08:44 UTC, rajlful commented on hikisapi.py
> +        with open('configuration_data', 'wb') as config:
Это функция берет конфиг с камеры, это файлик со специфическим расширением, который хранит все настройки камеры, и которые можно потом на камеру закгрузить. То есть конфиг по любом нужно писать в файл

2021-06-09 08:45 UTC, rajlful commented on settings.py
> +ipaddr='172.16.13.70'
Да, да, я же писал уже) Я с разных компуктеров работаю, мне удобно чтоб этот файл лежал на гите. А то что данные открыте это не страшно, она у меня локально

2021-06-09 09:12 UTC, rajlful commented on hikisapi.py
> +import logging
Не очень понял, что не так

2021-06-09 09:15 UTC, rajlful commented on hikisapi.py
> +import logging
а, понял

2021-06-09 09:17 UTC, rajlful commented on hikisapi.py
> +        with open('configuration_data', 'wb') as config:
Как это лучше тогда сделать ?

2021-06-09 09:17 UTC, rajlful commented on hikisapi.py
> +            print(decoded_event)
Смотрю в сторону psycopg и postgres

2021-06-09 17:04 UTC, Roxe322 commented on hikisapi.py
> +        with open('configuration_data', 'wb') as config:
а зачем писать его в файл на каждый вызов? переименую функцию тогда во что-то типа dump_camera_config
ну и вообще наверное опять же, должно быть лучше чистые
 функции - одна получает с камеры, другая - пишет в файл. третья - читает из файла, четвертая - пишет на камеру

2021-06-09 17:07 UTC, Roxe322 commented on hikisapi.py
> +            print(decoded_event)
С базой наверное попозже будем работать, расскажу на следующем созвоне. Начать лучше с sqlite. Пока можешь просто в логи писать ивенты, например. Отдельный логфайл для них завести. Плюс щас непонятно, как ты ее планируешь прерывать, если она висит бесконечно :) 


По поводу шлет непрерывно, возможно стоит посмотреть в сторону генераторов и yield
https://habr.com/ru/post/132554/

2021-06-09 17:07 UTC, Roxe322 commented on hikisapi.py
> +import logging
👍

2021-06-15 06:22 UTC, merged